// <auto-generated />
using IEnumerableVsIQueryable;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IEnumerableVsIQueryable.Migrations
{
    [DbContext(typeof(BookContext))]
    [Migration("20250518134843_InitialCreate1")]
    partial class InitialCreate1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IEnumerableVsIQueryable.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 10,
                            Author = "Herbert Schildt",
                            Price = 52.12m,
                            Title = "Java: The Complete Reference"
                        },
                        new
                        {
                            Id = 11,
                            Author = "Joan Casteel",
                            Price = 167.53m,
                            Title = "Oracle 11g"
                        },
                        new
                        {
                            Id = 12,
                            Author = " Brahmanand Shukla",
                            Price = 37.99m,
                            Title = "Learn T-SQL"
                        },
                        new
                        {
                            Id = 13,
                            Author = "C++ Programming Language",
                            Price = 105.18m,
                            Title = "C++ Programming Language"
                        },
                        new
                        {
                            Id = 14,
                            Author = "Clive Campbell",
                            Price = 41.99m,
                            Title = "PYTHON PROGRAMMING"
                        },
                        new
                        {
                            Id = 15,
                            Author = " David Flanagan",
                            Price = 53.32m,
                            Title = "JavaScript: The Definitive"
                        },
                        new
                        {
                            Id = 16,
                            Author = "Steve Eichert",
                            Price = 45.99m,
                            Title = "LINQ In Action"
                        },
                        new
                        {
                            Id = 17,
                            Author = "Jon Skeet",
                            Price = 49.99m,
                            Title = "C# in Depth"
                        },
                        new
                        {
                            Id = 18,
                            Author = "Learning SQL",
                            Price = 46.26m,
                            Title = "Learning SQL"
                        },
                        new
                        {
                            Id = 19,
                            Author = "Fullstack Vue",
                            Price = 51.07m,
                            Title = "Fullstack Vue"
                        },
                        new
                        {
                            Id = 20,
                            Author = "The Road to React",
                            Price = 37.08m,
                            Title = "The Road to React"
                        },
                        new
                        {
                            Id = 21,
                            Author = "Dan Appleman",
                            Price = 44.99m,
                            Title = "Moving To VB.NET"
                        },
                        new
                        {
                            Id = 22,
                            Author = "Jeremy Wilken",
                            Price = 59.99m,
                            Title = "Angular in Action"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
